### ISSUE TITLE
Icona delle impostazioni non funzionante

### ISSUE THREAD

**Issue by Davvy80** [scheccia1/hagarbage#1]
![Image](https://github.com/user-attachments/assets/75d620c7-a6dd-4f2f-a5b2-4eb9787f762c)

Ciao a tutti,
quando facci click sull'icona dell'ingranaggio per aprire il pop-up delle impostazioni non funziona, non succede niente.
Di seguito il mio codice della card:
`type: entities
card_mod:
  style: |
    .card-header {
      padding: 0px 0px 0px 0px !important;
    }
show_header_toggle: "off"
entities:
  - type: section
    label: Raccolta Differenziata ♻️
  - type: custom:hui-element
    card_type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-elements
            image: /local/rifiuti/trasparente.png
            elements:
              - type: image
                entity: sensor.raccoltadifferenziata
                style:
                  top: 0%
                  left: 0%
                  transform: translate(0%,20%)
                state_image:
                  Nulla: /local/rifiuti/Nulla.png
                  Indifferenziato: /local/rifiuti/Indifferenziato.png
                  Plastica e metalli: /local/rifiuti/Plastica.png
                  Vetro: /local/rifiuti/Vetro.png
                  Carta e cartone: /local/rifiuti/Carta.png
                  Organico: /local/rifiuti/Organico.png
                  Organico e Vetro: /local/rifiuti/Organicoeresto.png
          - type: vertical-stack
            cards:
              - type: custom:button-card
                layout: icon_name_state2nd
                entity: sensor.giornosettimana
                name: Oggi è
                show_icon: true
                show_state: true
                icon: mdi:calendar-arrow-right
                styles:
                  grid:
                    - grid-template-columns: 30px auto
                  icon:
                    - padding: 0px 0px
                    - height: 30px
                    - width: 30px
                  card:
                    - "--ha-card-background": rgba(0, 0, 0, 0.0)
                    - "--ha-card-box-shadow": none
                    - "--ha-card-border-width": 0px
                    - height: 43px
                    - width: 190px
                  state:
                    - padding: 0px 10px
                    - justify-self: start
                    - font-family: Roboto, sans-serif
                    - font-size: 12px
                  name:
                    - padding: 0px 10px
                    - justify-self: start
                    - font-size: 12px
                    - color: var(--primary-text-color)
              - type: custom:button-card
                layout: icon_name_state2nd
                entity: sensor.raccoltadifferenziata
                name: >-
                  [[[ return "Ritiro dalle: " +
                  (states["input_datetime.raccolta_differenziata_notifiche_start_time"].state.split(":")[0]
                  + ":" +
                  states["input_datetime.raccolta_differenziata_notifiche_start_time"].state.split(":")[1]);
                  ]]]
                show_icon: true
                show_state: true
                icon: mdi:recycle
                styles:
                  grid:
                    - grid-template-columns: 30px auto
                  icon:
                    - padding: 0px 0px
                    - height: 30px
                    - width: 30px
                  card:
                    - "--ha-card-background": rgba(0, 0, 0, 0.0)
                    - "--ha-card-box-shadow": none
                    - "--ha-card-border-width": 0px
                    - height: 43px
                    - width: 190px
                  state:
                    - padding: 0px 10px
                    - justify-self: start
                    - font-family: Roboto, sans-serif
                    - font-size: 12px
                  name:
                    - padding: 0px 10px
                    - justify-self: start
                    - font-size: 12px
                    - color: var(--primary-text-color)
              - type: custom:button-card
                layout: icon_name_state2nd
                entity: sensor.giornoritiro
                name: Giorno del ritiro
                show_icon: true
                show_state: true
                icon: mdi:trash-can-outline
                styles:
                  grid:
                    - grid-template-columns: 30px auto
                  icon:
                    - padding: 0px 0px
                    - height: 30px
                    - width: 30px
                  card:
                    - "--ha-card-background": rgba(0, 0, 0, 0.0)
                    - "--ha-card-box-shadow": none
                    - "--ha-card-border-width": 0px
                    - height: 43px
                    - width: 190px
                  state:
                    - padding: 0px 10px
                    - justify-self: start
                    - font-family: Roboto, sans-serif
                    - font-size: 12px
                  name:
                    - padding: 0px 10px
                    - justify-self: start
                    - font-size: 12px
                    - color: var(--primary-text-color)
              - type: custom:button-card
                icon: hass:cog-outline
                show_icon: true
                styles:
                  grid:
                    - grid-template-columns: 30px auto
                  icon:
                    - padding: 0px 0px
                    - height: 20px
                    - width: 20px
                  card:
                    - "--ha-card-background": rgba(0, 0, 0, 0.0)
                    - "--ha-card-box-shadow": none
                    - "--ha-card-border-width": 0px
                    - height: 30px
                    - width: 30px
                tap_action:
                  action: fire-dom-event
                  browser_mod:
                    service: browser_mod.popup
                    data:
                      title: Impostazioni
                      style: >
                        --popup-background-color:
                        var(--secondary-background-color);

                        --dialog-backdrop-filter: blur(2em) brightness(0.75);
                      content:
                        type: entities
                        entities:
                          - entity: input_boolean.raccolta_differenziata_da_notificare
                          - entity: sensor.giorno_della_settimana
                          - entity: >-
                              input_datetime.raccolta_differenziata_notifiche_start_time
                          - entity: >-
                              input_datetime.raccolta_differenziata_notifiche_end_time
                          - entity: >-
                              input_number.frequenza_notifiche_raccolta_differenziata
                          - entity: input_select.raccolta_differenziata_lun
                          - entity: input_select.raccolta_differenziata_mar
                          - entity: input_select.raccolta_differenziata_mer
                          - entity: input_select.raccolta_differenziata_gio
                          - entity: input_select.raccolta_differenziata_ven
                          - entity: input_select.raccolta_differenziata_sab
                          - entity: input_select.raccolta_differenziata_dom
                          - type: divider
                          - type: divider
                          - entity: >-
                              input_boolean.raccolta_differenziata_seconda_settimana
                          - type: divider
                          - entity: input_select.raccolta_differenziata_lun2
                          - entity: input_select.raccolta_differenziata_mar2
                          - entity: input_select.raccolta_differenziata_mer2
                          - entity: input_select.raccolta_differenziata_gio2
                          - entity: input_select.raccolta_differenziata_ven2
                          - entity: input_select.raccolta_differenziata_sab2
                          - entity: input_select.raccolta_differenziata_dom2
 `
Grazie a chi mi aiuta

**Comment by Davvy80** [comment]
![Image](https://github.com/user-attachments/assets/ca9e9656-0237-41b1-89e2-09e49e15c60d)

**Comment by scheccia1** [comment]
non hai installato/attivato browser_mod deve essere visibile nel menu

**Comment by Davvy80** [comment]
> non hai installato/attivato browser_mod deve essere visibile nel menu

Ciao, browser_mod  è  installato, configurato, e funzionante, viene usato per altre card e funziona.
Qualche altra idea?

**Comment by scheccia1** [comment]
lo schema? non sò se è per come lo hai postato ma ad un certo punto non rispetta gli spazi.
```
                tap_action:
                  action: fire-dom-event
                  browser_mod:
                    service: browser_mod.popup
                    data:
                      title: Impostazioni
                      style: >
                        --popup-background-color:
                        var(--secondary-background-color);

                        --dialog-backdrop-filter: blur(2em) brightness(0.75);
                      content:
                        type: entities
                        entities:
                          - entity: input_boolean.raccolta_differenziata_google
                          - entity: input_boolean.raccolta_differenziata_alexa
                          - type: divider
                          - entity: input_boolean.raccolta_differenziata_da_notificare
                          - entity: sensor.giorno_della_settimana
                          - entity: >-
                              input_datetime.raccolta_differenziata_notifiche_start_time
                          - entity: >-
                              input_datetime.raccolta_differenziata_notifiche_end_time
                          - entity: >-
                              input_number.frequenza_notifiche_raccolta_differenziata
                          - entity: input_select.raccolta_differenziata_lun
                          - entity: input_select.raccolta_differenziata_mar
                          - entity: input_select.raccolta_differenziata_mer
                          - entity: input_select.raccolta_differenziata_gio
                          - entity: input_select.raccolta_differenziata_ven
                          - entity: input_select.raccolta_differenziata_sab
                          - entity: input_select.raccolta_differenziata_dom
                          - type: divider
                          - type: divider
                          - entity: >-
                              input_boolean.raccolta_differenziata_seconda_settimana
                          - type: divider
                          - entity: input_select.raccolta_differenziata_lun2
                          - entity: input_select.raccolta_differenziata_mar2
                          - entity: input_select.raccolta_differenziata_mer2
                          - entity: input_select.raccolta_differenziata_gio2
                          - entity: input_select.raccolta_differenziata_ven2
                          - entity: input_select.raccolta_differenziata_sab2
                          - entity: input_select.raccolta_differenziata_dom2

```
altro test che potresti fare e togliere tutto quello che c'e' dopo content e vedere se apre una pagina vuota.
